// William Wong
// This project is called the guessing game where the user
// has to try to guess a random number generated by the computer between 0-100
// 1. No global variables
// 2. No strings
// 3. You should include <iostream>, not stdio

#include <iostream>

using namespace std;

int main()
{

  //Below the program is initializing the variables
  //One of the most important ones is generating a random num
  // With srand() and setting it to be within the limits of 0-100
  
  char playAgain;
  char yesNo = 'y';
  int userInput = 0;
  srand(time(0));
  int compNum = rand()%101;
  int userGuesses = 0;

  //Sets up the game by asking the user to choose num between 0-100
  //Takes in the user input using cin
  //And for every guess the user takes their guess counter increases by 1
  
  cout << "Please guess a number between 1-100: ";
  cin >> userInput;
  userGuesses +=1;

  //This while loop allows the user to keep playing until their answer is no
  
  while (yesNo == 'y') {

    //If the users number is lower than computers num
    //This will print out that the users number is lower than the comp num
    
    if(userInput < compNum) {

      cout << "Your guess is too low. Guess again: ";
      cin >> userInput;
      userGuesses +=1;
      
    }

    //If the users number is higher than computers num
    //This will print out that the users number is highter then the comp num 

    if (userInput > compNum) {

      cout << "Your guess is too high. Guess again: ";
      cin >> userInput;
      userGuesses +=1;
      
    }

    //If the users num is equal to computers num it will tell the user they
    //guessed right and ask them if they want to play again
    //If they want to play again this program will generate a new random num
    //If not I will break the system and the program will stop 

    if (userInput == compNum) {

      cout << "You guessed the right number!" << endl;
      cout << "Number of guesses: " << userGuesses << endl;
      userGuesses = 0;
      cout << "Do you want to play again?: ";
      cin >> playAgain;

      if (playAgain == 'y') {

	compNum = rand()%101;

	cout << "Please guess a num between 0-100: ";
	cin >> userInput;
	userGuesses +=1;
	
      } else {

	cout << "Thanks for playing!";
	break;
	
     } 
    }
   }
  }

